export const factoryAbi = [
  {
    type: "function",
    name: "createPot",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "perPerson", type: "uint256" },
      { name: "partySize", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "payee", type: "address" },
      { name: "title", type: "string" },
    ],
    outputs: [{ name: "pot", type: "address" }],
  },
  {
    type: "function",
    name: "createPot",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "perPerson", type: "uint256" },
      { name: "partySize", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "payee", type: "address" },
      { name: "title", type: "string" },
      { name: "isPrivate", type: "bool" },
      { name: "secretHash", type: "bytes32" },
    ],
    outputs: [{ name: "pot", type: "address" }],
  },
  {
    type: "function",
    name: "potCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allPots",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "feeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "feeRecipient",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "event",
    name: "PotCreated",
    inputs: [
      { name: "pot", type: "address", indexed: true },
      { name: "organizer", type: "address", indexed: true },
      { name: "payee", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "perPerson", type: "uint256", indexed: false },
      { name: "partySize", type: "uint256", indexed: false },
      { name: "deadline", type: "uint256", indexed: false },
      { name: "title", type: "string", indexed: false },
      { name: "isPrivate", type: "bool", indexed: false },
    ],
  },
] as const;

export const potAbi = [
  {
    type: "function",
    name: "commit",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "commitWithSecret",
    stateMutability: "payable",
    inputs: [{ name: "secret", type: "bytes" }],
    outputs: [],
  },
  {
    type: "function",
    name: "rotateSecret",
    stateMutability: "nonpayable",
    inputs: [{ name: "newHash", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "isPrivate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "refunded",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "release",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "title",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  { type: "function", name: "expire", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "refund", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "state",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "commitCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "perPerson",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "partySize",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "deadline",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "token",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "payee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "organizer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "committed",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "contributors",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address[]" }],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
] as const;
